language: android
jdk: oraclejdk8
sudo: required

before_cache:
 -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 -rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

script:
 - ./gradlew clean
 - ./gradlew assembleDebug
 - ./gradlew assembleDebugAndroidTest

android:
  components:
    - tools
    - platform-tools

    - build-tools-26.0.2
    - android-27

after_failure:
  - cat app/build/reports/checkstyle.html
  - cat app/build/reports/lint-results.xml
  - cat app/build/reports/lint-results.html
  - cat app/build/reports/findbugs.html
  - cat app/build/reports/pmd.html
